name: firebase_admin
description: A port of the Firebase admin sdk to pure, idiomatic Dart code
version: 0.1.4
homepage: https://github.com/appsup-dart/firebase_admin

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  clock: ^1.0.0
  x509: ^0.2.2
  jose: '^0.3.2'
  dotenv: ^3.0.0
  openid_client: ^0.4.1
  firebase_dart: ^1.0.0-dev.31
  path: ^1.6.4
  meta: ^1.1.6
  http: ^0.13.0
  crypto_keys: ^0.3.0
  collection: ^1.14.11
  gcloud:
    git: git@github.com:dart-lang/gcloud.git
  #gcloud: '^0.7.3'

dev_dependencies:
  fake_async: ^1.0.0
  pedantic: ^1.9.0
  mockito: ^4.1.1
  test: ^1.16.5
